name: hadafi_application
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1



environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.6.0  
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1  
  firebase_auth_web: ^5.13.2  
  url_launcher: ^6.1.10
  http: ^1.2.2
  flutter_parsed_text: ^2.2.1  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.0.4
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  image_picker: ^0.8.8
  permission_handler: ^10.4.1
  google_ml_kit: ^0.13.0
  image: ^3.2.0
  file_picker: ^5.0.0
  syncfusion_flutter_pdf: ^21.1.36
  firebase_storage: ^12.4.3
  flutter_riverpod: ^2.6.1
  dartz: ^0.10.1
  fpdart: ^1.1.1
  dotted_border: ^2.0.0
  csv: ^6.0.0
  uuid: ^3.0.4
  routemaster: ^0.5.0
  any_link_preview: ^3.0.3
  intl: ^0.19.0
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - Hadafi/images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
